; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.5 on 2026-08-24 at 00:30:35
; total layer number: 25
; filament_density: 1.24,1.24,1.24,1.24
; filament_diameter: 1.75,1.75,1.75,1.75
; max_z_height: 5.05
; HEADER_BLOCK_END

; ... (cuerpo del G-code recortado para el fixture)

; filament used [mm] = 528.66, 1936.58, 247.20, 0.00
; filament used [cm3] = 1.27, 4.66, 0.59, 0.00
; filament used [g] = 1.58, 5.78, 0.74, 0.00
; total filament used [g] = 8.09
; total filament cost = 0.16
; total filament change = 6
; estimated printing time (normal mode) = 19m 17s
; estimated first layer printing time (normal mode) = 19s
; filament_density = 1.24,1.24,1.24,1.24
; filament_diameter = 1.75,1.75,1.75,1.75
