import type { FilamentUsage, SlicerReport } from "./types";

/**
 * Lee el resumen que todo laminador deja en comentarios del G-code (H-03).
 *
 * Es la misma idea que `slice_info.config` pero para un .gcode suelto: el peso y
 * el tiempo ya los calculó el laminador, y el peso incluye purga y soportes.
 * Sumar los movimientos E daría lo mismo con mucho más trabajo, así que primero
 * se leen los comentarios.
 *
 * Dialectos soportados:
 *   BambuStudio  ; total filament weight [g] : 7.49,3.39,1.73
 *                ; model printing time: 37m 25s; total estimated time: 43m 40s
 *   Orca / Prusa ; total filament used [g] = 8.09
 *                ; estimated printing time (normal mode) = 19m 17s
 */
export function parseGcodeSummary(text: string): SlicerReport | null {
  const weightGrams = readWeight(text);
  const printTimeSeconds = readTime(text);
  if (weightGrams === undefined && printTimeSeconds === undefined) return null;

  const filaments = readFilaments(text);
  const total =
    weightGrams ?? filaments.reduce((acc, f) => acc + f.grams, 0);
  if (!(total > 0)) return null;

  return {
    weightGrams: total,
    printTimeSeconds,
    filaments,
    layerCount: num(text, /^;\s*total layer number\s*[:=]\s*(\d+)/im),
    filamentChanges: num(text, /^;\s*total filament change\s*[:=]\s*(\d+)/im),
    producer: readProducer(text),
  };
}

function readWeight(text: string): number | undefined {
  // Orca / PrusaSlicer: un único escalar, ya sumado.
  const scalar = num(text, /^;\s*total filament used \[g\]\s*[:=]\s*([\d.]+)/im);
  if (scalar !== undefined) return scalar;

  // BambuStudio: una lista, un valor por filamento.
  const bambu = numList(text, /^;\s*total filament weight \[g\]\s*[:=]\s*([\d.,\s]+)$/im);
  if (bambu.length) return sum(bambu);

  // Último recurso: la lista por filamento sin total.
  const perFilament = numList(text, /^;\s*filament used \[g\]\s*[:=]\s*([\d.,\s]+)$/im);
  if (perFilament.length) return sum(perFilament);

  return undefined;
}

function readTime(text: string): number | undefined {
  // El "total estimated time" de Bambu incluye cambios de filamento y calentado;
  // es el que se parece al reloj de pared, así que va primero.
  const candidates: RegExp[] = [
    /total estimated time\s*[:=]\s*([0-9dhms\s]+)/i,
    /^;\s*estimated printing time \(normal mode\)\s*[:=]\s*([0-9dhms\s]+)/im,
    /^;\s*model printing time\s*[:=]\s*([0-9dhms\s]+)/im,
  ];
  for (const re of candidates) {
    const raw = text.match(re)?.[1];
    const secs = raw ? parseDuration(raw) : undefined;
    if (secs !== undefined && secs > 0) return secs;
  }
  return undefined;
}

function readFilaments(text: string): FilamentUsage[] {
  const grams =
    numList(text, /^;\s*total filament weight \[g\]\s*[:=]\s*([\d.,\s]+)$/im) ||
    [];
  const fallback = grams.length
    ? grams
    : numList(text, /^;\s*filament used \[g\]\s*[:=]\s*([\d.,\s]+)$/im);

  const meters = numList(text, /^;\s*total filament length \[mm\]\s*[:=]\s*([\d.,\s]+)$/im);
  const metersAlt = meters.length
    ? meters
    : numList(text, /^;\s*filament used \[mm\]\s*[:=]\s*([\d.,\s]+)$/im);

  const types = strList(text, /^;\s*filament_type\s*[:=]\s*([A-Za-z0-9,\s+-]+)$/im);

  return fallback
    .map((g, i) => ({
      id: i + 1,
      type: types[i],
      grams: g,
      meters: metersAlt[i] !== undefined ? metersAlt[i] / 1000 : undefined,
    }))
    // Los laminadores listan todos los slots, incluso los que no se usaron.
    .filter((f) => f.grams > 0);
}

function readProducer(text: string): string | undefined {
  const generated = text.match(/^;\s*generated by\s+(.+?)\s+on\b/im)?.[1];
  if (generated) return generated.trim();
  const bambu = text.match(/^;\s*(BambuStudio\s+[\d.]+)/im)?.[1];
  if (bambu) return bambu.trim();
  return undefined;
}

/** Acepta "19m 17s", "1h 2m 3s", "2d 1h 5m", "45s". */
export function parseDuration(raw: string): number | undefined {
  const parts = raw.matchAll(/(\d+(?:\.\d+)?)\s*([dhms])/gi);
  const unit: Record<string, number> = { d: 86400, h: 3600, m: 60, s: 1 };
  let total = 0;
  let found = false;
  for (const [, value, symbol] of parts) {
    total += parseFloat(value) * unit[symbol.toLowerCase()];
    found = true;
  }
  return found ? total : undefined;
}

function num(text: string, re: RegExp): number | undefined {
  const raw = text.match(re)?.[1];
  if (raw === undefined) return undefined;
  const value = parseFloat(raw);
  return Number.isFinite(value) ? value : undefined;
}

function numList(text: string, re: RegExp): number[] {
  const raw = text.match(re)?.[1];
  if (!raw) return [];
  return raw
    .split(",")
    .map((s) => parseFloat(s.trim()))
    .filter((n) => Number.isFinite(n));
}

function strList(text: string, re: RegExp): string[] {
  const raw = text.match(re)?.[1];
  if (!raw) return [];
  return raw.split(",").map((s) => s.trim()).filter(Boolean);
}

function sum(values: number[]): number {
  return values.reduce((a, b) => a + b, 0);
}

/**
 * Los comentarios de resumen viven al principio o al final del archivo, así que
 * leemos sólo las dos puntas. Un G-code puede pesar cientos de MB y no hay
 * ninguna razón para cargarlo entero en memoria.
 */
const EDGE_BYTES = 256 * 1024;

export async function readGcodeSummary(file: File): Promise<SlicerReport | null> {
  const head = await file.slice(0, EDGE_BYTES).text();
  const tail =
    file.size > EDGE_BYTES ? await file.slice(Math.max(0, file.size - EDGE_BYTES)).text() : "";
  return parseGcodeSummary(`${head}\n${tail}`);
}
